name: miki

on: 
  push:
    tags:
    - '*'

jobs:
  miki101:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: miki test nested
      run: git submodule foreach --recursive 'git checkout main && git pull'
    - name: Checkout Submodules
      run: git submodule update --init --recursive
    - name: Set up python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install test dependencies
      run: pip3 install ansible
    - name: create collection
      run: ansible-galaxy collection build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
