---
name: CI
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install test dependencies.
        run: pip3 install --user https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
      - name: install setuptools
        run: pip3 install setuptools
      - name: deploy
        run: |
          export TOWER_HOST=${{ secrets.ANSIBLE_URL }}
          export TOWER_USERNAME=${{ secrets.ANSIBLE_USER }}
          export TOWER_PASSWORD=${{ secrets.ANSIBLE_PASSWORD }}
          export TOWER_VERIFY_SSL=false
          awx job_templates list -f human
          awx job_templates launch 11 --monitor --wait --verbosity 0
